CREATE DATABASE IF NOT EXISTS tbs_db;
USE tbs_db;

CREATE TABLE Client (
    ClientID INT AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    IDNumber VARCHAR(13) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    PhoneNumber VARCHAR(15),
    IsVerified BOOLEAN DEFAULT FALSE,
    DateRegistered DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE OTP (
    OTPID INT AUTO_INCREMENT PRIMARY KEY,
    ClientID INT NOT NULL,
    OTPCode VARCHAR(6) NOT NULL,
    DateGenerated DATETIME DEFAULT CURRENT_TIMESTAMP,
    ExpiryTime DATETIME NOT NULL,
    IsUsed BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (ClientID) REFERENCES Client(ClientID)
);

CREATE TABLE Notification (
    NotificationID INT AUTO_INCREMENT PRIMARY KEY,
    ClientID INT NOT NULL,
    Type VARCHAR(20) NOT NULL,
    Message VARCHAR(255),
    DateSent DATETIME DEFAULT CURRENT_TIMESTAMP,
    Status VARCHAR(20) DEFAULT 'Sent',
    FOREIGN KEY (ClientID) REFERENCES Client(ClientID)
);

CREATE TABLE BusCard (
    BusCardID INT AUTO_INCREMENT PRIMARY KEY,
    ClientID INT NOT NULL,
    CardNumber VARCHAR(20) NOT NULL UNIQUE,
    Balance DECIMAL(10,2) DEFAULT 0.00,
    DateIssued DATE,
    FOREIGN KEY (ClientID) REFERENCES Client(ClientID)
);

CREATE TABLE BankCard (
    BankCardID INT AUTO_INCREMENT PRIMARY KEY,
    ClientID INT NOT NULL,
    CardNumber VARCHAR(20) NOT NULL,
    CardHolderName VARCHAR(100) NOT NULL,
    ExpiryDate VARCHAR(20) NOT NULL,
    BankName VARCHAR(50),
    FOREIGN KEY (ClientID) REFERENCES Client(ClientID)
);

CREATE TABLE Transaction (
    TransactionID INT AUTO_INCREMENT PRIMARY KEY,
    ClientID INT NOT NULL,
    BusCardID INT NOT NULL,
    BankCardID INT NOT NULL,
    Amount DECIMAL(10,2) NOT NULL,
    Status VARCHAR(20) DEFAULT 'Pending',
    TransactionDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ClientID) REFERENCES Client(ClientID),
    FOREIGN KEY (BusCardID) REFERENCES BusCard(BusCardID),
    FOREIGN KEY (BankCardID) REFERENCES BankCard(BankCardID)
);